version: "3.7"

services:
  api:
    build: .
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8001 --timeout 1800
    volumes:
      - .:/usr/src/app/
    expose:
      - 8001
    env_file:
      - ./env.env

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web